### ISSUE TITLE
Error After Update

### ISSUE THREAD

**Issue by ryancasler** [mbudnek/google-home-hubitat-community#101]
**Describe the bug**
After updating to the latest code, I get the following error.
2022-12-05 03:09:57.578 PMerrorgroovyx.net.http.HttpResponseException: status code: 403, reason phrase: Forbidden on line 204 (method updated)

**To Reproduce**
Save the app.

**Comment by ryancasler** [comment]
Also, the instructions for creating a new project are incorrect.   After Creating a Project there is no prompt called "Smart Home".  It takes me to a screen to select which APIs I want to include.  There also is no developer tab.

**Comment by ryancasler** [comment]
Yeah....I am going to have to completely uninstall everything and then re-add everything to Google Home.   Hours of work.   Not cool.

**Comment by mbudnek** [comment]
Does that happen even when you haven't entered anything for the new "Google Service Account Authorization" setting?

Also you shouldn't need to re-add everything.  If something's not working you can always revert back to the [previous version](https://github.com/mbudnek/google-home-hubitat-community/blob/62444c3aae41bdcef62bd820c0bdff7cef58555e/google-home-community.groovy) temporarily.

**Comment by ryancasler** [comment]
Well, on the Google Cloud Console, the project I created under Google Actions isn't listed.  And yes, I use the same account on both but I do have other google Cloud Console projects.  Several of them as a matter of fact.  I can import the project I created in the Google Cloud Console into Actions but not vice versa.

**Comment by mbudnek** [comment]
That explains the 403 error then.  You'll need to enable Home Graph and create a service account and key for the project corresponding to your Action.  Note that the project name should match the Action name that shows up on console.actions.google.com.  That's not necessarily the same as the display/invocation name of the Action.

**Comment by ryancasler** [comment]
Creating the Cloud Console project first and then importing that project into the Actions Console worked and got rid of the error when saving the app updates in Hubitat.
