### ISSUE TITLE
fail to update to latest version 0.36.1

### ISSUE THREAD

**Issue by stilny** [mbudnek/google-home-hubitat-community#102]
Trying to update in hubitat by package manager and by "copy paste" from groovy file here,
to latest version 0.36.1 ,getting error through package manager and if i do update manual,the version still 0.35.0 after copy/paste.
attached images of hubitat update failure message.
How can i update manual?
Thank you.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="754" alt="Screenshot_20221215_110437" src="https://user-images.githubusercontent.com/116232251/207967047-464d8d0e-e265-40f1-be95-2c204d5784bc.png">
<img width="534" alt="Screenshot_20221215_110144" src="https://user-images.githubusercontent.com/116232251/207967107-0a20c6fe-b176-4727-b95e-0f73c1967bb3.png">

<img width="534" alt="Screenshot_20221215_110144" src="https://user-images.githubusercontent.com/116232251/207967040-9dfc690a-6697-4063-9098-3174b2352dee.png">

**Additional context**

**Comment by mbudnek** [comment]
What error do you get when you manually paste the code?  Does it generate an error when you click save or later when you try to use the app?  If it's later, please paste any relevant lines from the Hubitat log for the app here.

**Comment by stilny** [comment]
When I  paste it, is no error ,but the version shown in hubitat 0.35.0 and update manager constantly notifying about new version and  fails to update to it.

If this version is ok and no need of further update,why it’s happening?

**Comment by mbudnek** [comment]
Manually updating the app won't be reflected in Hubitat Package Manager; it has no idea you did that.

When you try to update via HPM are there any errors in the Hubitat log?

**Comment by stilny** [comment]
Yes,there is a fatal error in log.

**Comment by mbudnek** [comment]
And it is?

**Comment by stilny** [comment]
I attached two screenshots in previos mail.Sent from my Galaxy
-------- Original message --------From: Miles Budnek ***@***.***> Date: 2022-12-16  23:48  (GMT+02:00) To: mbudnek/google-home-hubitat-community ***@***.***> Cc: stilny ***@***.***>, Author ***@***.***> Subject: Re: [mbudnek/google-home-hubitat-community] fail to update to latest version 0.36.1 (Issue #102) 
And it is?

**Comment by mbudnek** [comment]
I cannot see the screenshots you attached.  Can you post them directly to the issue thread instead of via email?

**Comment by stilny** [comment]
<img width="673" alt="log" src="https://user-images.githubusercontent.com/116232251/208198771-2f2fb9e0-dd20-4b10-aee4-328ec67f634e.png">

**Comment by stilny** [comment]
attached a log,also you have another printscreens that i am already attached here from hubitat

**Comment by mbudnek** [comment]
Could the issue be that your hub is overloaded and the app takes too long to install?  When updating the app manually how long does it take from when you click "save" to when it finishes?  It looks like HPM has a 5 minute timeout.  I wouldn't expect it to take that long, but it's really the only guess I have left.

Beyond that I would need to see what the actual error is, and HPM isn't logging it.  Since the error is only when updating via that app and not when updating manually and since I'm not able to reproduce it myself even with HPM I'm not sure there's much more I can do to help.  At this point it seems more likely you'll get your issue solved if you post over in the [HPM forum thread](https://community.hubitat.com/t/release-hubitat-package-manager-hubitatcommunity/94471)

**Comment by stilny** [comment]
It's not overloaded, all the other apps updating fine,just today updated webcore app. The problem is with this app only.Mannually apdate take 2 seconds .Hope somebody will find solution on hubitat.Sent from my Galaxy
-------- Original message --------From: Miles Budnek ***@***.***> Date: 2022-12-17  00:54  (GMT+02:00) To: mbudnek/google-home-hubitat-community ***@***.***> Cc: stilny ***@***.***>, Author ***@***.***> Subject: Re: [mbudnek/google-home-hubitat-community] fail to update to latest version 0.36.1 (Issue #102) 
Could the issue be that your hub is overloaded and the app takes too long to install?  When updating the app manually how long does it take from when you click "save" to when it finishes?  It looks like HPM has a 5 minute timeout.  I wouldn't expect it to take that long, but it's really the only guess I have left.
Beyond that I would need to see what the actual error is, and HPM isn't logging it.  Since the error is only when updating via that app and not when updating manually and since I'm not able to reproduce it myself even with HPM I'm not sure there's much more I can do to help.  At this point it seems more likely you'll get your issue solved if you post over in the HPM forum thread
