### ISSUE TITLE
De-Authorizing App in Google Home

### ISSUE THREAD

**Issue by jvmahon** [mbudnek/google-home-hubitat-community#106]
I recently migrated my Hubitat hub from a C7 to a C8 model.

As part of that, I have been trying to get Google Home community working again. To do that, I've created a new Project on Google Actions to set up Google Home Community with a new OAUTH and secret key for the new Hubitat C8.

Some issues . . . 
First, my "old" Projects for my old hub are still lingering around when I try to re-add the new Project for the new Hub. I've tried deleting the old Projects, but they still appear to be selectable in Google Home. I'm assuming that somewhere there is some database of OAUTH registered apps and I have to delete these somewhere. Anybody know?

![image](https://user-images.githubusercontent.com/15061942/223702141-2eb45cbc-d631-40fe-87cc-f7286457e507.png)

**Comment by mbudnek** [comment]
This is a known issue on Google's end.  See [this issue](https://issuetracker.google.com/issues/148664341) on their bug tracker.  It looks like they may finally be working on fixing it too.

**Comment by jvmahon** [comment]
Thanks for the reply. I've deleted the Projects (and they are now in the "Pending Deletion") queue - my hope is that once the timeout expires and they are permanently deleted, this may fix itself. As of now, there seems to be now way to reconnect Google Home Community with Hubitat (even after creating a new Project, I now get the error: 'The parameter "state" must be set in the query string'.

**Comment by mbudnek** [comment]
Like I said, it's a bug on Google's end.  The old `[test] Hubitat` entries will stay there until Google fixes their bug.

As for 'The parameter "state" must be set in the query string', that is an OAuth error.  Check that your OAuth client ID and client secret match the ones for the new hub and that the authorization and token URLs are correct.

**Comment by jvmahon** [comment]
It was the failure to set the "Scope" to "App" that was causing the problem. Working now.
