### ISSUE TITLE
Cannot link Google Home to [test] app

### ISSUE THREAD

**Issue by dcorrea78** [mbudnek/google-home-hubitat-community#110]
Recently, I updated the devices I want to control via the Google Home Community Hubitat app. When I went into the Google Home app to relink the Hubitat [test] app I created last year, I get an error stating" Could not reach [test] app server. Please try again" and my devices do not update. I verified the settings at console.actions.google.com with no success. Any idea what I can do to fix this? My devices that were previously linked still work, but I cannot add any new devices.

**Comment by mbudnek** [comment]
At what point in the process does it fail?  That will help narrow down what could be going wrong.

In addition, please enable debug logging in the Hubitat app and watch the Hubitat log while you attempt to sync with Google Home.  You should see the `SYNC` request and response data in the log.  Post that here and I can take a look at it.

**Comment by dcorrea78** [comment]
Thanks for the response and I figured it out. I did not specify the device type. so the additional devices were basically being ignored. Rookie Mistake.
