### ISSUE TITLE
Unable to save / build - google-home-community.groovy - in  Platform Version 2.3.5.152

### ISSUE THREAD

**Issue by Hosk32** [mbudnek/google-home-hubitat-community#111]
When trying to save in Hubitat New Driver receive the following error.

No signature of method: Script1.definition() is applicable for argument types: (java.util.LinkedHashMap) values: [[name:Google Home Community, namespace:mbudnek, author:Miles Budnek, ...]] on line 97

Thanks Mark

**Comment by Hosk32** [comment]
<img width="1036" alt="192_168_1_169_driver_save_and_78057_pdf_and_MQTT_Topics_and_Messages___Zigbee2MQTT" src="https://github.com/mbudnek/google-home-hubitat-community/assets/50300924/d26bea79-919d-47f4-9b0f-90ec882b01f6">

**Comment by mbudnek** [comment]
It looks like you tried to install the app as a driver.  Make sure you paste the app code into the editor from the "Apps code" page rather than the "Drivers code" page.

**Comment by Hosk32** [comment]
Hi mbudnek - thanks - my bad - much appreciated - and thanks for getting back so fast.
Regards Mark
