### ISSUE TITLE
Device offline in google home

### ISSUE THREAD

**Issue by jarnoni** [mbudnek/google-home-hubitat-community#115]
Was able to add smart wing blinds but device shows as offline in google home app.

**Comment by mbudnek** [comment]
Please provide more details if you need help.  How did you configure you blinds in the Hubitat app (what traits did you give it, and how did you configure those traits)?

**Comment by jarnoni** [comment]
Sorry wish I would've replied earlier so I could post the exact solution. It was just a setting in the device type in the app.
