### ISSUE TITLE
Local Fulfillment?

### ISSUE THREAD

**Issue by ryancasler** [mbudnek/google-home-hubitat-community#27]
Have you given any thought to adding local fulfillment to the project?  I started looking at it through the Smart Home Actions docs and it looks like you're already 95% of the way there.  All that would need to be added is one line in the sync response, a definition of the endpoint and some NodeJS code for the discovery.  I tried to see what I could come up with but alas, it is just slightly over my head.  But I'm going to keep working on it...if you get motivated enough to want to do it, I'd be more than happy to help you test what you come up with.  
Here's the link I was reviewing:
https://developers.google.com/assistant/smarthome/develop/local

Thanks again!!!

**Comment by mbudnek** [comment]
I've thought about it, and would like to implement local fulfillment at some point.  This was actually one of my early drivers for wanting to build this integration in the first place.  The more I've looked into it and though about it though, the less sure I've become that it will really buy much in terms of performance or privacy though.

The voice and language processing still has to happen on Google's servers, so it's not like it will make the entire process happen locally.  Basically, the request flow would just be
```
Home Device/Phone -> Google Servers -> Home Device -> HE
```
which isn't that much different than existing flow of
```
Home Device/Phone -> Google Servers -> Hubitat Servers -> HE
```

**Comment by ryancasler** [comment]
The big difference would no longer be the need to rely on the Hubitat cloud servers.  So, if Hubitat shuts down those servers, we wouldn't be left out in the cold as far as voice assistant control goes.  Also if someone were to not want to expose their hub to the hubitat servers, they would still be able to use Google Assistant.  That's the benefits I was thinking about.

**Comment by mbudnek** [comment]
Sadly we would still be reliant on Hubitat's servers for authentication, account linking, and syncing.

I definitely do think it's worth pursuing local fulfillment; I'm just skeptical that it will provide a significant advantage over the cloud fulfillment path.

**Comment by ryancasler** [comment]
That's disappointing.

**Comment by amdbuilder** [comment]
I could be mistake, but it sounds like they push portions of the processing to the local device.  It's almost as if they are caching frequent requests on the device, minimizing cloud interaction to fulfill requests.  They do note "running actions locally", which would imply independence from the "cloud".

https://www.youtube.com/watch?v=aaaUSeQGLAA&feature=youtu.be

**Comment by leemarsh2010** [comment]
Would incorporating the new GH local control capability bypass the "can't connect to Hubitat right now" errors some of us get daily?

**Comment by Gassgs** [comment]
Has there been any additional thought on this? I would be willing to do anything i could to help/test. I use mostly touch controls with google via my phone and Google/Nest displays. I believe that would all be locally processed?

**Comment by mbudnek** [comment]
I don't currently have any plans to work on this in the immediate future.  The stuff I talked about in #42 is my top priority right now.
