### ISSUE TITLE
Error controlling scenes

### ISSUE THREAD

**Issue by amdbuilder** [mbudnek/google-home-hubitat-community#34]
**Describe the bug**
Error triggering "Good Night" routine when controlling scene.

`groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'C', no possible valid JSON value or punctuation could be recognized. on line 1250 (handleAction)`

**To Reproduce**
1. Create virtual switch
2. In GHC App create Device Type (Device Type: Switch - Google Type: Scene - Traits: On/Off - Separate commands).
3. Associate switch with device trait and sync
4. In Google Routine chose Adjust Scenes and select the virtual switch - Save
5. Ask Google to run Routine
6. All actions completed, except triggering Scene.  Google notes it's unable to reach the action
7. Check Hubitat log and see error

**Expected behavior**
Google adjusts the scene accordingly

**Screenshots**

**Additional context**

**Comment by mbudnek** [comment]
Interesting.  That error is due to the hacky way I'm working around the fact Hubitat won't let you define your own exception classes.  There should be a debug level log entry just before it with the real error message.
Can you try with debug logging on?  There are two specific log entries that will help track this down.  One will look something like
```
{inputs=[{context={locale_country=US, locale_language=en}, intent=action.devices.EXECUTE, payload={commands=[...]}}], requestId=3380284334565926728}
```
And the other will be something like
```
Error executing command ${commandName} on device ${deviceName}: ${errorMessage}
```
There may be a couple of the first one if your routine also turns some switches/lights/plugs on or off.

**Comment by amdbuilder** [comment]
I haven't had a chance to do more in-depth testing for you, but did get a screenshot of the log data last night on my phone.  I started watching the log just before triggering Google, and those entries are the result.

I'll try to do more testing this weekend, when it's unlikely to disturb the better half.

![image](https://user-images.githubusercontent.com/437374/80161201-9a1a5c80-859d-11ea-84ff-07ef5fe02d9a.png)

**Comment by amdbuilder** [comment]
The device in question (193).

![image](https://user-images.githubusercontent.com/437374/80161434-612eb780-859e-11ea-8220-41b66d05a3c0.png)

**Comment by mbudnek** [comment]
It looks like the Google routine is using the ActivateScene command from the Scene trait instead of On/Off.  Try setting the scene up using the Scene trait.

**Comment by amdbuilder** [comment]
Apologies for the slow response.  Switching the trait resolved the problem, and as far as I can tell hasn't affected our interaction.  I suspect I defaulted to on/off as that's how we are used to interacting with the devices.

Thanks for the quick assistance!!!!!
