### ISSUE TITLE
Documentation of debugging methods for GHA

### ISSUE THREAD

**Issue by selfish** [mbudnek/google-home-hubitat-community#45]
**Before requesting changes to device traits, please check [Google's Documentation](https://developers.google.com/assistant/smarthome/traits) to see if the change is supported on their side.**

**Is your feature request related to a problem? Please describe.**
I'm working on implementing the Channel Trait, and I have an error coming from Google. "Oops I failed" type of thing.
When I try to use the command ("set tv to channel 1") in actions console it says the command is unavailable in the simulator, and searches did not yield solutions.

**Describe the solution you'd like**
Could you assist in finding the right documentation on how to debug my work?
If you could help me with gathering the knowledge of the best practice here, I'm happy to document that in the project's wiki or in the readme, to help others easily develop for this package.

**Describe alternatives you've considered**
I'm jut hoping to get some of your knowledge on debugging the action so I can both solve a problem I'm facing and document the process for others.

**Additional context**
n/a

**Comment by mbudnek** [comment]
This is something I also don't have much insight into.  You can turn on debug logging in the Hubitat app, and the app will log all of the requests it gets from Google.  Other than that though, I don't really know if there's any way to get debugging info from the Google side.

**Comment by selfish** [comment]
Fair enough. I'll share documentation in case I'm able to find anything interesting.
In this instance, the request doesn't even reach the hubitat log, and that's where I was struggling.

Thank you.
