### ISSUE TITLE
New user configuration

### ISSUE THREAD

**Issue by 4noraisin** [mbudnek/google-home-hubitat-community#47]
Hello, I don't know if this is the correct please to be asking this, but I am trying to follow the setup steps to grant this functionality to my HE/Google Home. I have followed all the steps with success but the device still doesn't show up in my google account. I have the app installed on my hubitat, I have the smart home action, and I configured the device type. When I go to add the [test] app name, I am able to sign in, choose my hub, and authorize the device I am trying to use with this app. Once I click authorize, the screen says "signing in" and then refreshes back to the add a service screen. If I go to add [test] app name again, I can see that the device is already authorized, but it is not showing up in my google home for me to add to a room. ect.

I have the latest hub that just came out a few months ago, and confirmed that the hub is up to date.

Any help is greatly appreciated. 

Thank you so much

**Comment by mbudnek** [comment]
If you turn on debug logging in the Hubitat app and then say "Hey Google, sync my smart home devices", do you see a SYNC message appear in the Hubitat log?

**Comment by 4noraisin** [comment]
Thank you for the quick reply!

The only entry I see in the log for the App is:

app:142020-11-03 11:41:36.139 am errorjava.lang.NullPointerException: Cannot get property 'name' on null object on line 216 (deviceTypePreferences)

That was a few hours ago...

**Comment by mbudnek** [comment]
In that case check the fulfilment URL configured in your Google Action.  It should follow the pattern `https://cloud.hubitat.com/api/{your hub ID}/apps/{app ID}/action`, so if your Hub ID is `b6f42456-67bd-4044-915e-aa02fa7d8e14` and your app ID is `123`, then the fulfillment URL should be `https://cloud.hubitat.com/api/b6f42456-67bd-4044-915e-aa02fa7d8e14/apps/123/action`.

**Comment by 4noraisin** [comment]
I was able to resolve that piece of it. For some reason, on Hubitat it had the app downloaded twice. I couldn't get to the login screen on the google side without correcting this error. I removed the duplicate app, and used the correct App ID and got further in the process. 

I am still unable to add the app to Google home it seems. I click on [test] app name, login, my devices are populated and selected, I click authorize, and then it says signing in and refreshes me to the add services screen.

**Comment by mbudnek** [comment]
The other thing to check would be your OAuth settings in the Google Action.  Specifically check the token URL; it should be `https://oauth.cloud.hubitat.com/oauth/token`.

**Comment by 4noraisin** [comment]
Confirmed that is what I have set, no extra spaces anywhere.

**Comment by 4noraisin** [comment]
Are you supposed to see this as a linked service if added successfully? I currently do not see it as a linked service or in any room in my google home.

**Comment by mbudnek** [comment]
You won't see any devices until you configure and select them in the Hubitat app.  There is no separate device for the hub itself or anything.  You do have to have at least one device selected before the app can be linked to Google Home successfully.

**Comment by 4noraisin** [comment]
I think this maybe where I am confused. Please see my screenshots of my app on hubitat and the screen on my phone,
![screenshot1](https://user-images.githubusercontent.com/64961466/98117180-591dd180-1e77-11eb-95ed-2d14050363ca.PNG)
![screenshot2](https://user-images.githubusercontent.com/64961466/98117182-591dd180-1e77-11eb-80e5-76062d014af6.PNG)
![screenshot3](https://user-images.githubusercontent.com/64961466/98117183-591dd180-1e77-11eb-9ed1-d8d1a27f7bbc.PNG)
![2020-11-04 08 20 40](https://user-images.githubusercontent.com/64961466/98117185-59b66800-1e77-11eb-84ab-e1ca9f43cd0d.png)

**Comment by 4noraisin** [comment]
I have not been able to get this working, but also don't know what to try
next :-(

**Comment by mbudnek** [comment]
In that case, with debug logging turned on in the Hubitat app, do you see any log activity after you tap "authorize"?  If so, post those log messages here and I can take a look at them.

**Comment by 4noraisin** [comment]
I really appreciate you taking the time to help me. I feel like I'm going
crazy. The only thing in the log is saying that I turned on logging:

dev:2 <http://192.168.50.147/logs#pastdev2>2021-05-08 09:18:31.656 pm warn
<http://192.168.50.147/device/edit/2>description logging is: true
dev:2 <http://192.168.50.147/logs#pastdev2>2021-05-08 09:18:31.654 pm warn
<http://192.168.50.147/device/edit/2>debug logging is: true

When I click on the Warn button, it brings me to the parent device (I am
trying to update the component device with this program) and Setvalue is
red and blank and under Device Information the type* is red but set to
Hampton Bay Zigbee Fan Controller (the only other options for Hampton bay
is Light component and Fan Component, but this is the parent device so it
should be correct. The component device which I am trying to get working is
set to Hampton Bay Fan Component, and the light is set to Hampton Bay Light
Component (also red but is working))

Thank you

Adam

**Comment by mbudnek** [comment]
There should be logging from the Google Home Community app itself.  If there isn't, that means Google's requests are never making it to the Hubitat app.  The most likely culprits are the OAuth settings and the Fulfillment URL in your Google Action.

For OAuth, check to make sure your client ID and client secret match those in Hubitat's app code editor.  Especially the client secret.  Hubitat doesn't let you copy from that field in some browsers, and Google masks it in its form, so it's easy to accidentally paste the wrong thing in there without noticing.  Also keep in mind that the OAuth scopes are case-sensitive.  "App" and "app" are not the same thing.

For the Fulfillment URL, it should follow the pattern https://cloud.hubitat.com/api/{your hub ID}/apps/{app ID}/action, so if your Hub ID is b6f42456-67bd-4044-915e-aa02fa7d8e14 and your app ID is 123, then the fulfillment URL should be https://cloud.hubitat.com/api/b6f42456-67bd-4044-915e-aa02fa7d8e14/apps/123/action.

**Comment by 4noraisin** [comment]
I confirmed the url is correct with the hub id and app id. In the test tab,
I am able to give commands to the fan and have them work as well.

I have enabled logging in the Google community app but don't see anything
in the events tab. In the status tab I see the latest entry is me turning
on debuglogging.

**Comment by 4noraisin** [comment]
Yeah I don't see the log at all. Google Home is not getting to the point of
asking the app for a list of devices and that is my issue. In my logs I
only see a log for Google home, not Google home community. This is very
strange.

**Comment by 4noraisin** [comment]
Please don't think I'm crazy, but I just randomly tested again and it's
working! I don't think I did anything different, but everything is updated
and working! Thank you so much for your help! I really appreciate it!

**Comment by mbudnek** [comment]
Huh, well that's good that its working at least.  I'm going to go ahead and close this issue then.  Feel free to open another one or ask in the Hubitat forum thread if you have any further issues.
