### ISSUE TITLE
Couldn't update the setting. Check your connection"

### ISSUE THREAD

**Issue by ClemmerC** [mbudnek/google-home-hubitat-community#61]
**Describe the bug**
Continue to get this error after following the full instructions "Could't update the setting. Check your connection"

**To Reproduce**
Follow the full tutorial all the way to step 27, and the error "Couldn't update the setting. Check your connections" appears.

**Expected behavior**
The exposed devices to sync with Google Home

**Screenshots**

**Additional context**
{
  "insertId": "1c0cmcsg4m47q78",
  "jsonPayload": {
    "syncLog": {
      "syncs": [
        {
          "requestId": "8355305146507511458",
          "httpLatencyMsec": "70",
          "status": "BACKEND_FAILURE"
        }
      ]
    }
  },
  "resource": {
    "type": "assistant_action_project",
    "labels": {
      "project_id": "blinds-904a7"
    }
  },
  "timestamp": "2021-03-09T04:31:34.068445255Z",
  "severity": "ERROR",
  "logName": "projects/blinds-904a7/logs/assistant_smarthome%2Fassistant_smarthome_logs",
  "receiveTimestamp": "2021-03-09T04:31:34.068445255Z"
}

**Comment by mbudnek** [comment]
Did you ever get this figured out?

**Comment by ClemmerC** [comment]
Yes.....there's a single character mistake in the GitHub guide that you
copy and paste.   I can't remember what it is off the top of my head, I
think in the comments of this forum it's been typed correctly a couple of
time and I had just noticed it was ever so slightly different at the
beginning or at the end.

**Comment by ClemmerC** [comment]
Excuse me, I meant to say it's typed correctly in the comments of the
hubitat forum.

**Comment by mbudnek** [comment]
Cool.  Closing this issue since you were able to resolve the issue.
