### ISSUE TITLE
Cannot "Sign In" via Google Home app - The parameter "state" must be set in the query string.

### ISSUE THREAD

**Issue by mattbaird** [mbudnek/google-home-hubitat-community#62]
**Describe the bug**
I recreated the Google Smart Home action and reinstalled the Google Home Community app.

Following the instructions here: https://github.com/mbudnek/google-home-hubitat-community/ under the heading "Creating the Google smart home Action", the second part "To create your Google smart home Action:".

At step 24, I authenticate via U/P, the next screen comes up, I select my home, I wait roughly 30 seconds and get the message The parameter "state" must be set in the query string.

**To Reproduce**
Create the google smart home action according to the instructions here: https://github.com/mbudnek/google-home-hubitat-community/
Authenticate
See issue

**Expected behavior**
I would expect for authentication to complete so I can add devices to the Google Home Mobile App that are configured in the Hubitat Google Home Community App.

**Additional context**
I had to reinstall your app and recreated the smart home action.
I triple-checked my smart home action for proper configuration.
I tweaked the name of the smart home action to help google get the back end sorted.
I have been testing this over a full day in between creating the smart home action and trying to authenticate.
I have 8 items exposed to Google home, as instruction by instruction 26
in the console, in the Test section, clicking the "Talk to Hubitate Google Integration" results in an error: We're sorry, but something went wrong. Please try again.

**Comment by mbudnek** [comment]
That error indicates a configuration issue in your Google Action.  Triple-check the your OAuth client info under the account linking section.  If you see that error before you select devices it indicates that the OAuth client ID is incorrect.  If you see it after selecting devices it indicates the OAuth client secret is incorrect.  Keep in mind that Hubitat blocks copying from the OAuth client secret field on some browsers, so make sure you've actually copied the correct thing (this is an especially easy mistake to make since the Google Actions UI doesn't show the client secret you entered).

**Comment by mattbaird** [comment]
Fair enough, thanks for the feedback and direction.

I went through another time VERY CAREFULLY (I'm a software developer myself).

I Sign in (although the sign-in page is different depending on when I run this process, sometimes I have social + u/p, other times It says "login as USERNAME".

I select the home.

I select the devices (I exposed 3 in Google Home Community App"

I get the "<project> is linked" message

and then I get "Something went wrong. Try Again".

The Google logs seem to indicate an INVALID_ARGUMENT


{
insertId: "1u1ty70g168rn0x"
jsonPayload: {
syncLog: {
syncs: [
0: {
status: "INVALID_ARGUMENT"
httpLatencyMsec: "249"
requestId: "6406861727463383336"
}
]
}
}
resource: {
type: "assistant_action_project"
labels: {
project_id: "hubitat-8bf28"
}
}
timestamp: "2021-04-06T23:42:41.312634238Z"
severity: "ERROR"
logName: "projects/hubitat-8bf28/logs/assistant_smarthome%2Fassistant_smarthome_logs"
receiveTimestamp: "2021-04-06T23:42:41.312634238Z"
}

I've tried unlinking and re-linking, I've tried resetting the test in the actions console. Nothing is working.

Any thoughts?

**Comment by mbudnek** [comment]
That new error points to an issue with the device type configuration.  Make sure all of your device types have at least one trait, and that all of the traits have all of the required config options set.  If you can't find the issue turn on debug logging in the Hubitat app and watch the log while you do a sync (pull down to refresh in the Google Home app or "Hey Google, sync my smart home devices").  You should see the sync request and response in the logs.  Post those here and I can take a look.  They should look something like this:
```
app:650 2021-04-06 11:01:33.116 pm debug [requestId:11083057449690963886, payload:[devices:[<a bunch of device config stuff here>]]]
app:650 2021-04-06 11:01:31.553 pm debug {inputs=[{intent=action.devices.SYNC}], requestId=11083057449690963886}
```

**Comment by mattbaird** [comment]
Indeed that was it. Thank you.
