### ISSUE TITLE
tempatures doesnt sync

### ISSUE THREAD

**Issue by killahkazx** [mbudnek/google-home-hubitat-community#78]
**Describe the bug**
no longer have the to use the command "all temperatures"  with google home get a  "cannot not connect to hubitat"

**Additional context**
log shows 

2021-05-15 04:33:44.072 pm errororg.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead on line 4033 (handleAction)

**Comment by mbudnek** [comment]
Can you provide a bit more information?  What type of devices do you have with the Temperature Setting trait?  How are those device types configured in the Google Home Community app?  From the error you posted, it seems like you have something with both Temperature Setting and either Brightness or (non discrete) Open/Close and the latter trait is misconfigured.

**Comment by killahkazx** [comment]
i have 2 xiaomi devices and a smarthings front door sensor. previously i could ask google "all temperatures" and have google tell me all the temperatures. now it say "sorry i cant connect to the hubitat" after testing it appears the smart things contact sensor is not sending tempature

**Comment by mbudnek** [comment]
Your error points at the Open/Close trait for that device being misconfigured, and that's causing an error when querying the state of the device.  How is your Open/Close trait configured for that device?  Since it's a contact sensor it should almost certainly have the "Discrete Only Open/Close" setting turned on.

**Comment by killahkazx** [comment]
That did it, sorry it was. Such an easy fix.  T worked previously and after the update it stopped.
