### ISSUE TITLE
Certain Devices Aren't Showing Up as Selectable, Even With Proper Traits

### ISSUE THREAD

**Issue by jacobgraf** [mbudnek/google-home-hubitat-community#98]
**Describe the bug**
Some devices are not selectable in certain device categories, even though they support the required traits.

For example, this Inovelli On/Off Switch LZW30 (https://cln.sh/vXWRwhbjuGbsLaIpGLcE) should be selectable in this custom Device Type called 'Light (On/Off)' (https://cln.sh/53WhFiRS7GXDP3BtLhc9), but it doesn't (https://cln.sh/eTWeW5QKvd4AO8M7eIEt).

**Additional context**
I have a few other devices exhibiting similar behavior. Mainly the Zooz Double Switch. I have two different drivers and one shows up and the other doesn't. Both use the same traits.

Is there a way to force devices to show up in a Device Type list if you know they are eligible for that Device Type, or maybe there's a way to loosen the criteria for what devices show up as eligible for selection and which ones don't?

**Comment by mbudnek** [comment]
Your switches almost certainly don't report the "Light" capability, but rather just the "Switch" capability.  Change your "Device Type" to "Switch".

**Comment by jacobgraf** [comment]
Ok. Hmm. I figured since the trait was set to type switch and the trait on the device itself was switch, it should work. How do I find out what the device type is? Would the type "light" mean it's a bulb? Just trying to clarify. I know where to look to determine the trait and values, but I'm a bit unclear how to determine the device "type" so I make sure to set it appropriately in your plugin. Thanks for your help!

**Comment by mbudnek** [comment]
The "Device Type" field is just a filter for which devices will appear in the list to select from.  It's just a list of all of Hubitat's device capabilities.  Sadly Hubitat doesn't show what capabilities a device has anywhere in the UI.

For the most part devices will implement the capabilities corresponding to what the device is.  So a switch will have the "Switch" capability, a bulb will have the "Light" capability, etc.  You could always choose "Actuator", which should cover any device that you can control, or "Sensor", which should cover all sensors.

**Comment by jacobgraf** [comment]
That clarifies a lot! Much appreciated and thanks for making this plugin! It makes the Google side of things sooooo much more awesome!
